import { useState } from 'react';
import { useData } from '@/contexts/DataContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Team } from '@/types';
import { useToast } from '@/hooks/use-toast';

interface TeamFormProps {
  team?: Team;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSuccess?: () => void;
}

export function TeamForm({ team, open, onOpenChange, onSuccess }: TeamFormProps) {
  const { addTeam, updateTeam } = useData();
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    name: team?.name || '',
    autoAssignClients: team?.autoAssignClients || false,
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      if (team) {
        await updateTeam(team.id, formData);
        toast({
          title: 'Success',
          description: 'Team updated successfully',
        });
      } else {
        await addTeam({
          id: '', // Will be generated by backend
          ...formData,
          createdAt: new Date().toISOString(),
        });
        toast({
          title: 'Success',
          description: 'Team created successfully',
        });
      }
      onSuccess?.();
      onOpenChange(false);
    } catch (error) {
      toast({
        title: 'Error',
        description: error instanceof Error ? error.message : 'Failed to save team',
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{team ? 'Edit Team' : 'Create Team'}</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="name">Team Name</Label>
            <Input
              id="name"
              value={formData.name}
              onChange={(e) => setFormData(prev => ({ ...prev, name: e.target.value }))}
              required
            />
          </div>
          <div className="flex items-center space-x-2">
            <Checkbox
              id="autoAssignClients"
              checked={formData.autoAssignClients}
              onCheckedChange={(checked) => 
                setFormData(prev => ({ ...prev, autoAssignClients: checked === true }))
              }
            />
            <Label htmlFor="autoAssignClients">Auto-assign clients</Label>
          </div>
          <div className="flex justify-end gap-2">
            <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
              Cancel
            </Button>
            <Button type="submit" disabled={loading}>
              {loading ? 'Saving...' : team ? 'Update' : 'Create'}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
}

